name: DESIGN3D
favicon: null
layout_spectrum: 0.6406069253571332
typography_spectrum: 0.8382149413228035
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8092982701491565
  lightness: 0.4932072665542364
  saturation: 0.37022241041995585
  rhythmicContrast: 0.961831663036719
purpose: []
